# .release-please.yml

# Specify the release type (options: "semantic" or "gcp")
release-type: semantic

# Specify the branch to monitor for changes
branch: main

# Specify any additional configuration options as needed

